# Generated by Django 3.2.4 on 2021-11-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='location',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.CharField(default='available', max_length=60, null=True),
        ),
    ]
