# Generated by Django 3.2.4 on 2021-11-14 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phoneno', models.IntegerField(null=True)),
                ('cnic', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=60, null=True)),
                ('address', models.CharField(max_length=120, null=True)),
                ('skils', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
