# Generated by Django 3.2.4 on 2021-11-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='cnic_back_pic',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='worker',
            name='cnic_front_pic',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='worker',
            name='gender',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
