# Generated by Django 3.2.4 on 2021-11-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0003_rename_skils_worker_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
