# Generated by Django 3.2.4 on 2021-11-21 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0002_auto_20211116_0027'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Worker', '0004_worker_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('budget', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('offer_at', models.DateTimeField(auto_now_add=True)),
                ('offer_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Buyer.work')),
            ],
        ),
    ]
