# Generated by Django 3.2.4 on 2021-11-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0005_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_to',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
