# Generated by Django 3.2.4 on 2021-11-14 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_services_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
